In [20]:
import numpy as np

display(np.__version__)
display(np.__config__.show())

'1.23.2'

openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFI

None

In [21]:
a = list(range(100000000))

def test():
    for i in range(len(a)):
        a[i] += 1

%time test()


CPU times: total: 5.55 s
Wall time: 5.56 s


In [22]:
%time a = [n+1 for n in range(100000000)]

CPU times: total: 6.5 s
Wall time: 6.49 s


In [23]:
b = np.arange(100000000)
%time c = b + 1

CPU times: total: 125 ms
Wall time: 128 ms


In [24]:
data = [1, 2, 3, 4, 5]
nd = np.array(data)
print(nd, type(nd), nd.dtype, nd.shape, nd.size, sep=', ')

[1 2 3 4 5], <class 'numpy.ndarray'>, int32, (5,), 5


In [25]:
data = [1.1, 2.2, 3.3, 4.4, 5.5]
nd = np.array(data)
print(nd, type(nd), nd.dtype, nd.shape, nd.size, sep=', ')

[1.1 2.2 3.3 4.4 5.5], <class 'numpy.ndarray'>, float64, (5,), 5


In [26]:
data = np.array([[1,2,3,], [4,5,6], [7,8,9]])
nd = np.array(data)
print(nd, type(nd), nd.dtype, nd.shape, nd.size, sep=', ')

[[1 2 3]
 [4 5 6]
 [7 8 9]], <class 'numpy.ndarray'>, int32, (3, 3), 9


In [27]:
print(3 in nd)

True


In [28]:
print(nd.sum(axis=0), nd.sum(axis=1), nd.sum()) # 행방향의 합(2D to 1D), 열방향의 합(2D to 1D), 전체 합(2D to scalar)

[12 15 18] [ 6 15 24] 45
