In [2]:
import numpy as np
import pandas as pd
pd.__version__

'1.4.3'

In [5]:
s = pd.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [8]:
print(s.index, s.values) # index 제거하고 값만 가져옴

RangeIndex(start=0, stop=5, step=1) [1 2 3 4 5]


In [9]:
s = pd.Series([1, 2, 3, 4, 5], index=['a','b','c','d','e']) # index는 list나 tuple로 줄것
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
s = pd.Series({'a':1, 'b':2})
s

a    1
b    2
dtype: int64

In [12]:
for k, v in s.items(): # 한 행의 정보를 tuple로 보내줌
    print(f'{k}:{v}')

a:1
b:2


In [16]:
s = pd.Series([1, 2, 3, 4, 5], index=['a','b','c','d','e'])
print(s[0], s['b'], s.get('f',0)) # 'f' 없을때 0으로 출력 (s['f'] >> error)

1 2 0


In [25]:
s = pd.Series([1, 2, 3, 4, 5], index=['a','b','c','d','e'])
s1 = s[:3]
print(s1)
s2 = s[:3].copy()       # s[:3] window 생성, s[:3].copy() window의 사본 생성
print(s2)           
s1[0] = 10
s2[0] = 10              # 원본도 같이 수정됨.. slicing은 복사가 아니다!
print(s1, s)
print(s2, s)

a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64
a    10
b     2
c     3
dtype: int64 a    10
b     2
c     3
d     4
e     5
dtype: int64
a    10
b     2
c     3
dtype: int64 a    10
b     2
c     3
d     4
e     5
dtype: int64


In [22]:
s1 = s[[True, False, True, False, True]]
s1

a    1
c    3
e    5
dtype: int64

In [27]:
s > 3       # fancy indexing, 값이 copy 된다는 것이 특징

a     True
b    False
c    False
d     True
e     True
dtype: bool

In [28]:
s1 = s[s > 3]
s1

a    10
d     4
e     5
dtype: int64

In [29]:
s1 = s[(s >= 2) & ( s <= 4 )]
s1

b    2
c    3
d    4
dtype: int64

In [32]:
s1 = [['c','b']]
s1

c    3
b    2
dtype: int64

In [39]:
s = pd.Series([1, 2, 3, 4, 5, np.NAN]) # NAN : Not a number, 결측치 통계치에 영향을 준다...
s

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64


In [36]:
print(s.sum(), s.count(), s.mean()) # count 5? 6? 일반적으로는 5

15.0 5 3.0


In [38]:
c = s[s > 3].sum()
c

9.0

In [41]:
df = pd.DataFrame({'A': [1, 2, 3],
                    'B': [4, 5, 6], 
                    'C': [7, 8, 9]},
                    index = ['2022-01-01', '2022-01-02', '2022-01-03'])
df

A  B  C
2022-01-01  1  4  7
2022-01-02  2  5  8
2022-01-03  3  6  9

In [42]:
print(df.values, df.index, df.columns)

[[1 4 7]
 [2 5 8]
 [3 6 9]] Index(['2022-01-01', '2022-01-02', '2022-01-03'], dtype='object') Index(['A', 'B', 'C'], dtype='object')


In [43]:
df['A']     # 열은 그냥 가져올수 있음. 열 index 고정, 1차원 정보.

2022-01-01    1
2022-01-02    2
2022-01-03    3
Name: A, dtype: int64

In [44]:
df[:'2022-01-01'] # 행을 가져오려면 : 필요함. 열 index & 값으로 2차원 정보.

A  B  C
2022-01-01  1  4  7

In [48]:
df['A'][:'2022-01-01'] # 1개 data 선택하면 scalar 값 return

2022-01-01    1
Name: A, dtype: int64

In [50]:
df = pd.DataFrame({'A' : [1, 2, 3],
                    'B': [4, 5, 6], 
                    'C': [7, 8, 9]},
                    index = pd.date_range(start='2022-01-01', periods = 3))
df

A  B  C
2022-01-01  1  4  7
2022-01-02  2  5  8
2022-01-03  3  6  9

In [51]:
df.index # freq='D' : 1일 단위

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03'], dtype='datetime64[ns]', freq='D')

In [52]:
df[:'01/01/2022']

A  B  C
2022-01-01  1  4  7

In [55]:
df1 = df.loc['01/01/2022']    #loc 하면 transpose 되서 indexing 다시됨
df1

A    1
B    4
C    7
Name: 2022-01-01 00:00:00, dtype: int64

In [56]:
df1 = df.loc[:, 'A']        # 최근엔 이 방법 많이 씀
df1

2022-01-01    1
2022-01-02    2
2022-01-03    3
Freq: D, Name: A, dtype: int64

In [57]:
df1 = df.loc[:, 'A':'C'] 
df1

A  B  C
2022-01-01  1  4  7
2022-01-02  2  5  8
2022-01-03  3  6  9

In [96]:
# B열이 5보다 큰 행을 출력
df.loc[:, 'B' ] > 5
df1 = df.loc[df.loc[:, 'B'] > 5]
df1

A  B  C
2022-01-03  3  6  9

In [101]:
# 2022-01-02 값 중에 5보다 큰 열을 출력                 ## 여기 시험!!
df1 = df.loc[:, df.loc['2022-01-02'] > 5]
df1

C
2022-01-01  7
2022-01-02  8
2022-01-03  9

In [108]:
df = pd.DataFrame({'A' : [1, 2, 3, np.nan],
                    'B': [5, 6, 7, np.nan], 
                    'C': [9, np.nan, 11, np.nan],
                    'D': [np.nan, 14, 15, np.nan]},
                    index = pd.date_range(start='2022-01-01', periods = 4))
df

A    B     C     D
2022-01-01  1.0  5.0   9.0   NaN
2022-01-02  2.0  6.0   NaN  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  NaN  NaN   NaN   NaN

In [110]:
df.isnull().sum() / len(df)     # 각 열들의 NaN 개수

A    0.25
B    0.25
C    0.50
D    0.50
dtype: float64

In [114]:
df.info()               # Dtype이 숫자가 아니면 고민해야 함

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2022-01-01 to 2022-01-04
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       3 non-null      float64
 1   B       3 non-null      float64
 2   C       2 non-null      float64
 3   D       2 non-null      float64
dtypes: float64(4)
memory usage: 160.0 bytes


In [115]:
df1 = df.dropna() # NaN 포함된 행 삭제
df1

A    B     C     D
2022-01-03  3.0  7.0  11.0  15.0

In [116]:
df1 = df.dropna(axis=1) # NaN 포함된 열 삭제
df1

Empty DataFrame
Columns: []
Index: [2022-01-01 00:00:00, 2022-01-02 00:00:00, 2022-01-03 00:00:00, 2022-01-04 00:00:00]

In [117]:
df.mean()   # axis=0 이 default

A     2.0
B     6.0
C    10.0
D    14.5
dtype: float64

In [118]:
df1 = df.fillna(0)
df1

A    B     C     D
2022-01-01  1.0  5.0   9.0   0.0
2022-01-02  2.0  6.0   0.0  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  0.0  0.0   0.0   0.0

In [119]:
df1.mean()  # axis=0 이 default

A    1.50
B    4.50
C    5.00
D    7.25
dtype: float64

In [120]:
df1 = df.fillna(df.mean())  # 통계적으로 흔들리지 않을 값 채워본 예시
df1

A    B     C     D
2022-01-01  1.0  5.0   9.0  14.5
2022-01-02  2.0  6.0  10.0  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  2.0  6.0  10.0  14.5

In [121]:
df1.mean()

A     2.0
B     6.0
C    10.0
D    14.5
dtype: float64

In [122]:
df1 = df.fillna({'A':0, 'B':6, 'C':10, 'D':14}) # 원하는 값으로 채우기
df1

A    B     C     D
2022-01-01  1.0  5.0   9.0  14.0
2022-01-02  2.0  6.0  10.0  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  0.0  6.0  10.0  14.0

In [123]:
df = pd.DataFrame({'A' : [1, 2, 3, np.nan],
                    'B': [5, 6, 7, np.nan], 
                    'C': [9, np.nan, 11, np.nan],
                    'D': [np.nan, 14, 15, np.nan]},
                    index = pd.date_range(start='2022-01-01', periods = 4))
df

A    B     C     D
2022-01-01  1.0  5.0   9.0   NaN
2022-01-02  2.0  6.0   NaN  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  NaN  NaN   NaN   NaN

In [125]:
df1 = df.interpolate()      # 기본은 선형, 중간값을 구할 수 있으면 앞뒤값의 평균, 맨 앞은 채울수X, 맨 뒤의 NaN의 경우 (앞의 값만)
df1

A    B     C     D
2022-01-01  1.0  5.0   9.0   NaN
2022-01-02  2.0  6.0  10.0  14.0
2022-01-03  3.0  7.0  11.0  15.0
2022-01-04  3.0  7.0  11.0  15.0